name: Build and Test Matrix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    name: ${{ matrix.os }} - ${{ matrix.num_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        num_type: [Fixed32, Fixed64, Float32, Float64, Float80]
        exclude:
          - os: windows-latest
            num_type: Float80
          - os: macos-latest
            num_type: Float80

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure with CMake
        run: |
          cmake -B build \
                -DCALC_NUM_TYPE=${{ matrix.num_type }} \
                -DCALC_TESTS=ON \
                -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure
